[package]
name = "example-worker-concurrent"
edition = "2024"
[dependencies]
bumpalo = { version = "3.19.1", features = ["allocator_api"] }
futures = "0.3.31"
tokio = { version = "1.47.1", features = [
    "io-util",
    "rt",
    "macros",
    "rt-multi-thread",
    "io-std",
    "time",
] }
