[package]
name = "example-elm-formatter"
edition = "2024"
[dependencies]
bumpalo = { version = "3.19.1", features = ["allocator_api", "collections"] }
[profile.release]
opt-level = 3
codegen-units = 1
